### ISSUE TITLE
compile multi-line selector error

### ISSUE THREAD

**Issue by cheneywan** [reworkcss/css-whitespace#15]
``` coffee
cw = require 'css-whitespace'

console.log cw """
html, body, div, span, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
abbr, address, cite, code,
del, dfn, em, img, ins, kbd, q, samp, a,
small, strong, sub, sup, var,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section, summary,
time, mark, audio, video
  clear: none
"""
```

output:

``` css
htmlbodydivspanobjectiframe;

h1h2h3h4h5h6pblockquotepre;

abbraddresscitecode;

deldfnemimginskbdqsampa;

smallstrongsubsupvar;

dldtddolulli;

fieldsetformlabellegend;

tablecaptiontbodytfoottheadtrthtd;

articleasidecanvasdetailsfigcaptionfigure;

footerheaderhgroupmenunavsectionsummary;

time,
mark,
audio,
video {
  clear: none;
}
```
