### ISSUE TITLE
Long comma-separated lists with newlines compile incorrectly

### ISSUE THREAD

**Issue by matthewmueller** [reworkcss/css-whitespace#7]
Something like this:

``` sass
blockquote:before, blockquote:after,
q:before, q:after
  content: ''
  content: none
```

Will yield:

``` css
blockquote:beforeblockquote:after;

q:before,
q:after {
  content: '';
  content: none
}
```
